# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


  app.form.type.profile:
        class: AppBundle\Form\ProfileType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

  app.form.type.project:
          class: AppBundle\Form\ProjectType
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - { name: form.type }

  app.form.type.cv:
          class: AppBundle\Form\CurriculumvitaeType
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - { name: form.type }

  app.form.registration:
          class: AppBundle\Form\Admin\UserType
          tags:
              - { name: form.type, alias: app_user_registration }

  app.form.type.cvproject:
          class: AppBundle\Form\CurriculumvitaeProjectType
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - { name: form.type }

  login_listener:
          class: 'AppBundle\EventListener\LoginListener'
          arguments: ['@security.authorization_checker', '@router', '@event_dispatcher']
          tags:
              - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }